name = "cloudflare-docker-proxy-1"
compatibility_date = "2023-12-01"
main = "src/index.js"  # 这是你构建的 Worker 入口文件路径

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "libcuda.so"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "exmaple.com"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.shawhnt.site", custom_domain = true },
  { pattern = "quay.shawhnt.site", custom_domain = true },
  { pattern = "gcr.shawhnt.site", custom_domain = true },
  { pattern = "k8s-gcr.shawhnt.site", custom_domain = true },
  { pattern = "k8s.shawhnt.site", custom_domain = true },
  { pattern = "ghcr.shawhnt.site", custom_domain = true },
  { pattern = "cloudsmith.shawhnt.site", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.shawhnt.site", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
